package com.rasyidcode.remarsphotos_dotaheroes.network

import com.squareup.moshi.Json

data class DotaHero(
	@Json(name="img")
	val img: String? = null,
	@Json(name="primary_attr")
	val primaryAttr: String? = null,
	@Json(name="attack_range")
	val attackRange: Double? = null,
	@Json(name="attack_type")
	val attackType: String? = null,
	@Json(name="cm_enabled")
	val cmEnabled: Boolean? = null,
	@Json(name="roles")
	val roles: List<String?>? = null,
	@Json(name="icon")
	val icon: String? = null,
	@Json(name="base_mana")
	val baseMana: Double? = null,
	@Json(name="localized_name")
	val localizedName: String? = null,
	@Json(name="base_health")
	val baseHealth: Double? = null,
	@Json(name="legs")
	val legs: Double? = null,
	@Json(name="id")
	val id: Double? = null,
	@Json(name="str_gain")
	val strGain: Double? = null,
	@Json(name="base_armor")
	val baseArmor: Double? = null,
	@Json(name="night_vision")
	val nightVision: Double? = null,
	@Json(name="attack_rate")
	val attackRate: Double? = null,
	@Json(name="base_mana_regen")
	val baseManaRegen: Double? = null,
	@Json(name="base_attack_max")
	val baseAttackMax: Double? = null,
	@Json(name="base_int")
	val baseInt: Double? = null,
	@Json(name="int_gain")
	val intGain: Double? = null,
	@Json(name="base_str")
	val baseStr: Double? = null,
	@Json(name="move_speed")
	val moveSpeed: Double? = null,
	@Json(name="agi_gain")
	val agiGain: Double? = null,
	@Json(name="turn_rate")
	val turnRate: Double? = null,
	@Json(name="attack_point")
	val attackPoint: Double? = null,
	@Json(name="name")
	val name: String? = null,
	@Json(name="base_attack_min")
	val baseAttackMin: Double? = null,
	@Json(name="projectile_speed")
	val projectileSpeed: Double? = null,
	@Json(name="base_attack_time")
	val baseAttackTime: Double? = null,
	@Json(name="base_agi")
	val baseAgi: Double? = null,
	@Json(name="day_vision")
	val dayVision: Double? = null,
	@Json(name="base_health_regen")
	val baseHealthRegen: Double? = null,
	@Json(name="base_mr")
	val baseMr: Double? = null
)
